"use client";

import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ChevronDown, ChevronUp, Loader2, Sparkles } from "lucide-react";

interface Props {
  personId: string;
  personName: string;
}

export function HistoricalContext({ personId, personName }: Props) {
  const [state, setState] = useState<"idle" | "loading" | "loaded" | "error">("idle");
  const [content, setContent] = useState("");
  const [expanded, setExpanded] = useState(true);

  async function generate() {
    setState("loading");
    try {
      const res = await fetch("/api/generate-context", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ personId, contextType: "historical_snapshot" }),
      });
      if (!res.ok) throw new Error("Request failed");
      const data = await res.json();
      setContent(data.content);
      setState("loaded");
    } catch {
      setState("error");
    }
  }

  if (state === "idle") {
    return (
      <Card className="border-amber-200 bg-amber-50/60 dark:border-amber-900/40 dark:bg-amber-950/20">
        <CardContent className="p-4 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
          <div>
            <p className="font-medium text-amber-900 dark:text-amber-300 text-sm flex items-center gap-1.5">
              <Sparkles className="h-3.5 w-3.5" />
              Historical Context
            </p>
            <p className="text-xs text-stone-500 dark:text-stone-400 mt-0.5">
              AI-generated narrative of what life looked like during{" "}
              {personName.split(" ")[0]}&rsquo;s lifetime
            </p>
          </div>
          <Button
            onClick={generate}
            size="sm"
            className="shrink-0 bg-amber-700 hover:bg-amber-600 text-white gap-2"
          >
            <Sparkles className="h-3.5 w-3.5" />
            Generate
          </Button>
        </CardContent>
      </Card>
    );
  }

  if (state === "loading") {
    return (
      <Card className="border-amber-200 bg-amber-50/60 dark:border-amber-900/40 dark:bg-amber-950/20">
        <CardContent className="p-6 flex items-center justify-center gap-3 text-amber-700 dark:text-amber-400">
          <Loader2 className="h-4 w-4 animate-spin" />
          <span className="text-sm">Researching historical context…</span>
        </CardContent>
      </Card>
    );
  }

  if (state === "error") {
    return (
      <Card className="border-red-200 bg-red-50/50 dark:border-red-900/40 dark:bg-red-950/20">
        <CardContent className="p-4 flex items-center gap-3">
          <p className="text-sm text-red-700 dark:text-red-300 flex-1">
            Couldn&rsquo;t generate context. Make sure GEMINI_API_KEY is set.
          </p>
          <Button variant="ghost" size="sm" onClick={generate}>
            Retry
          </Button>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="border-amber-200 bg-amber-50/30 dark:border-amber-900/40 dark:bg-amber-950/10">
      <CardHeader
        className="pb-3 cursor-pointer select-none"
        onClick={() => setExpanded(!expanded)}
      >
        <div className="flex items-center justify-between">
          <CardTitle className="font-serif text-lg text-amber-900 dark:text-amber-300 flex items-center gap-2">
            <Sparkles className="h-4 w-4" />
            Historical Context
          </CardTitle>
          {expanded ? (
            <ChevronUp className="h-4 w-4 text-stone-400" />
          ) : (
            <ChevronDown className="h-4 w-4 text-stone-400" />
          )}
        </div>
      </CardHeader>
      {expanded && (
        <CardContent className="pt-0 space-y-3">
          {content.split("\n\n").filter(Boolean).map((para, i) => (
            <p
              key={i}
              className="text-sm text-stone-700 dark:text-stone-300 leading-relaxed"
            >
              {para}
            </p>
          ))}
          <p className="text-xs text-stone-400 dark:text-stone-500 flex items-center gap-1 pt-1 border-t border-stone-100 dark:border-stone-800">
            <Sparkles className="h-3 w-3" />
            Generated by Gemini AI · Educational context, not a substitute for primary sources
          </p>
        </CardContent>
      )}
    </Card>
  );
}
