# Confirmed Genealogical Records — Manning Family Puerto Rican Ancestry
## Research Date: April 17, 2026 (v2 — primary source documents incorporated)
## Sources: FamilySearch, Ancestry.com, HijosdeCoamoPR, Geneanet, EnciclopediaPR,
##          Primary birth/death/marriage certificates (12 documents reviewed)

---

## COMPLETE CONFIRMED LINEAGE (maternal branch — paternal surnames)

```
Keith David Manning Jr.
  └── Mother: Virginia Mestre
        ├── Grandmother: Silvia Belén  [BELÉN = her father's surname]
        │     └── Grandfather: Pedro Mestre
        │           └── Great-grandfather: Pedro Mestre Vázquez (1889–1962)  ✅ FamilySearch L812-RM7
        │                 ├── Great-great-grandfather: [Unknown Mestre]  born est. 1850–1870
        │                 └── Great-great-grandmother: [Unknown Vázquez]  born est. 1860–1870
        │
        └── (Echevarría/López line — connects through Virginia's maternal side)
              Great-grandmother: María Inés López Echevarría  (28 Apr 1912 – 2013)  ✅
                    ├── Father: Eustaquio López y Ortiz  (~1885 – ?)  ✅
                    │     ├── Grandfather: Elías López  (natural de Peñuelas)  ✅
                    │     └── Grandmother: Juana Ortiz/Orta  (natural de Yauco)  ✅
                    └── Mother: Benigna Echevarría  (13 Mar 1888 – 19 Jul 1981)  ✅
                          ├── Father: Pedro Villa  (natural de Yauco)  ✅
                          └── Mother: Dolores Echevarría  (1864 – 10 Dec 1950)  ✅  [Mulata]
                                └── Mother: María Echevarría  (natural de Guánica)  ✅
                                      [possibly = María Almodovar Echevarría  (~1818–1928)  ✅  [Negra]]
                                            └── Son: Ventura Echevarría  (death declarant)  ✅
```

**SLAVERY CONNECTION:**
- 1872 Slave Registry: Felipe (#1185, pardo, ~1820, enslaved by Juan Irizarry, Yauco)
- Dolores Echevarría (b. 1864) = born into slavery, age ~8 in 1872 Irizarry household
- Echevarría surname adopted at emancipation 1873 from prior enslaver named Echevarría

---

## OPEN QUESTION — CRITICAL

**Is "María Echevarría" (Dolores's mother) the same person as "María Almodovar Echevarría" (~1818–1928)?**

- Option A (same person): Almodovar surname was dropped in later records. Dolores is María Almodovar's direct daughter.
- Option B (different people): María Echevarría is a daughter of María Almodovar, making Dolores her granddaughter. This would add one generation.

Both are "natural de Guánica" and carry Echevarría. This must be resolved from civil or church records.

---

## CONFIRMED RECORDS — DIRECT ANCESTORS

### Keith David Manning Jr.
- Primary researcher, present generation

### Virginia Mestre
- Mother of Keith. Maiden surname: Mestre (paternal). Oral history confirmed.

### Silvia Belén  [Gen 2 — grandmother]
- **CRITICAL NOTE:** Belén is her PATERNAL surname — her father's last name was Belén.
- Her father's first name remains unknown.
- Married: Pedro Mestre (grandfather)
- Lived: Guánica / Barrio Carenero, Puerto Rico

### Pedro Mestre  [Gen 2 — grandfather]
- Son of Pedro Mestre Vázquez (1889–1962)
- Died when Keith was approximately 12 years old
- Estimated birth: 1915–1945
- Full name and maternal surname still unconfirmed
- **Status:** UNCONFIRMED — census search pending

---

### Pedro Mestre Vázquez (1889–1962)  ✅ CONFIRMED — Great-Grandfather
- **FamilySearch Profile:** L812-RM7
- **URL:** ancestors.familysearch.org/en/L812-RM7/pedro-mestre-vázquez-1889-1962
- **Born:** 1889  |  **Died:** 1962
- **Paternal surname:** Mestre  |  **Maternal surname:** Vázquez
- His mother was a Vázquez woman (search: Yauco ~1860–1890)
- Father of Keith's grandfather (Pedro Mestre)
- His own father (great-great-grandfather) reportedly still alive during Keith's grandfather's lifetime
- **Confidence:** CONFIRMED

---

### María Inés López Echevarría (28 Apr 1912 – 2013)  ✅ CONFIRMED — Great-grandmother
- **Source:** ACTA DE NACIMIENTO, Folio 14, Number 14, Guánica, P.R.
- **Born:** April 28, 1912 (declared May 1, 1912), Guánica, Puerto Rico
- **Died:** 2013 (oral history), age 101
- **Father:** Eustaquio López y Ortiz (~22 at birth, bracero, natural de Yauco)
- **Mother:** Benigna Echevarría (declarant on birth certificate)
- **Paternal grandparents:** Elías López (natural de Peñuelas) + Juana Ortiz (natural de Yauco)
- **Maternal grandparents:** Pedro Villa (natural de Yauco, Calle Victoria) + Dolores Echevarría (natural de Yauco, Calle Victoria)
- **Witnesses at birth registration:** Ramón Sánchez (Carpintero, Ponce) + Luis Antonio Palermo
- **Confidence:** CONFIRMED from primary document

---

### Eustaquio López y Ortiz (~1885–?)  ✅ CONFIRMED
- **Sources:** 1907 marriage record (Yauco) + 1912 birth certificate (Guánica)
- **Born:** ~1885 (age 22 at June 1907 marriage), natural de Yauco
- **Race:** Trigueño
- **Occupation:** Bracero (sugar cane field worker)
- **Father:** Elías López (natural de Peñuelas)
- **Mother:** Juana Ortiz (natural de Yauco; recorded as "Juana Orta" in 1907 marriage)
- **Married:** Benigna Echevarría, June 16, 1907, Yauco, Puerto Rico
- **Signed marriage record as:** "Eustaquio Looper"
- **Address circa 1912:** Calle Victoria, Guánica
- **Children confirmed:** María Inés López Echevarría (b. 1912) + Pedro Juan López Echevarria (b. 1919)
- **Confidence:** CONFIRMED

---

### Benigna Echevarría (13 Mar 1888 – 19 Jul 1981)  ✅ CONFIRMED
- **Sources:** 1907 marriage record + 1981 death certificate (No. 152) + 1912 birth certificate
- **Born:** March 13, 1888 (Guánica or Yauco area)
- **Died:** July 19, 1981, Ponce hospital, Puerto Rico. Age 93.
- **Race:** Mulata (1907 marriage record); listed as Blanco on 1981 death cert (racial classification changed over time)
- **Occupation:** Doméstica
- **Father:** Pedro Villa (natural de Yauco, Calle Victoria) — confirmed from daughter María Inés's 1912 birth cert
- **Mother:** Dolores Echevarría (natural de Yauco / Guánica) — confirmed from marriage record + death cert
- **Married:** Eustaquio López y Ortiz, June 16, 1907, Yauco
- **Natural child** — no father listed in her own marriage record (born to Dolores Echevarría outside of recorded marriage)
- **Last address:** Casón Ochoa #47, Guánica, Puerto Rico
- **Death informant:** Margarita Toro López (nieta/granddaughter)
- **Buried:** July 20, 1981, Municipal Cemetery Guánica
- **Cause of death:** Cerebral Thrombosis + Aspiration Pneumonia
- **Confidence:** CONFIRMED from multiple primary documents

---

### Dolores Echevarría (1864 – 10 Dec 1950)  ✅ CONFIRMED
- **Source:** Death certificate No. 143, District 27, Guánica, P.R.
- **Born:** 1864, Guánica, Puerto Rico
- **Died:** December 10, 1950, 8 PM, Barrio Carenero, Guánica, P.R. Age 86.
- **Race:** Mulata
- **Status:** Widow
- **Mother:** María Echevarría (natural de Guánica, P.R.)
- **Father:** Unknown — not listed in any confirmed record
- **Death informant:** Francisco López (nieto/grandson)
- **Cause:** Cardiovascular disease
- **SLAVERY NOTE:** Born 1864 — approximately 9 years before abolition (1873). Was almost certainly enslaved as a child. Per Gemini analysis, she appears as Dolores, age ~8, in the 1872 Slave Registry under Juan Irizarry, Yauco District 5.
- **Confidence:** CONFIRMED from primary document

---

### María Almodovar Echevarría (~1818 – 17 Jan 1928)  ✅ CONFIRMED
- **Source:** Death certificate No. 409, Guánica, P.R.
- **Born:** ~1818 (age 110 at death), Guánica, Puerto Rico
- **Died:** January 17, 1928, 10:30 PM, Calle Dr. Veve, Guánica, P.R.
- **Age at death:** 110 years (ciento diez) — remarkable longevity
- **Race:** Negra
- **Status:** Widow
- **Occupation:** Labores domésticas (domestic labor)
- **Parents:** Unknown to death declarant
- **Declarant:** Ventura Echevarría (en su carácter de hijo — as her son)
- **Witnesses:** Pedro Vázquez (Agricultor, Sabana Grande) + José Vázquez (Bracero, Sabana Grande)
  - NOTE: These Vázquez witnesses from Sabana Grande may connect to the Vázquez line of Pedro Mestre Vázquez (1889–1962)
- **Certified by:** Dr. J. García Quevedo
- **SLAVERY NOTE:** Born ~1818 — enslaved for approximately 55 years until abolition (1873). Survived to 110.
- **Confidence:** CONFIRMED from primary document

---

### Pedro Villa  ✅ CONFIRMED (placement)
- **Source:** María Inés López birth certificate (1912)
- **Role:** Father of Benigna Echevarría
- **Natural de:** Yauco, Puerto Rico
- **Address:** Calle Victoria, Guánica (circa 1912)
- **Partner:** Dolores Echevarría
- **Birth/death dates:** Unknown
- **Confidence:** CONFIRMED placement; dates unknown

---

### Elías López  ✅ CONFIRMED (placement)
- **Sources:** 1907 marriage record + 1912 birth certificate
- **Natural de:** Peñuelas, Puerto Rico
- **Role:** Father of Eustaquio López y Ortiz
- **Birth/death dates:** Unknown
- **Confidence:** CONFIRMED placement

---

### Juana Ortiz (Orta)  ✅ CONFIRMED (placement)
- **Sources:** 1907 marriage record (as "Juana Orta") + 1912 birth certificate (as "Juana Ortiz")
- **Natural de:** Yauco, Puerto Rico
- **Role:** Mother of Eustaquio López y Ortiz
- **Birth/death dates:** Unknown
- **Confidence:** CONFIRMED placement

---

### María Echevarría  ✅ CONFIRMED (placement — identity disputed, see Open Question above)
- **Source:** Dolores Echevarría death certificate (1950)
- **Role:** Mother of Dolores Echevarría
- **Natural de:** Guánica, P.R.
- **Birth/death dates:** Unknown
- **Confidence:** CONFIRMED placement; possibly same person as María Almodovar Echevarría

---

### Ventura Echevarría  ✅ CONFIRMED (placement)
- **Source:** María Almodovar Echevarría death certificate (1928)
- **Role:** Son of María Almodovar Echevarría; death declarant
- **Surname:** Echevarría — inherited from his mother
- **Birth/death dates:** Unknown
- **Confidence:** CONFIRMED placement

---

### Pedro Juan López Echevarria (22 Oct 1919 – 2008)  ✅ CONFIRMED
- **Source:** Ancestry genealogy record
- **Born:** October 22, 1919, Guánica, Puerto Rico
- **Died:** 2008
- **Mother:** Benigna Echevarría ✅
- **Father:** Eustaquio López y Ortiz ✅
- **Sibling of:** María Inés López Echevarría (same parents, same double surname pattern)
- **URL:** ancestry.com/genealogy/records/pedro-juan-lópez-echevarria-24-139kgqd
- **Confidence:** CONFIRMED

---

### Felipe (#1185)  ✅ CONFIRMED (1872 Slave Registry)
- **Source:** 1872 Puerto Rico Slave Registry, page 297, entry #1185
- **Enslaved by:** Dª Juana / Dn Juan Irizarry, Yauco, Puerto Rico
- **Age in 1872:** 52 → born ~1820
- **Race:** Pardo
- **Natural de:** Puerto Rico
- **FamilySearch:** Catalog #177782 (Registro Central de Esclavos)
- **Possible identity:** Felipe Echevarría — Gemini analysis places him as María Almodovar's partner/father of Dolores
- **Confidence:** CONFIRMED record exists; family connection = POSSIBLE

---

### Don Juan Irizarry  ✅ CONFIRMED (slavery-era enslaver)
- **Source:** 1872 Puerto Rico Slave Registry, Yauco District 5
- **Role:** Documented enslaver of Felipe (#1185) and possibly Dolores (~age 8, 1872)
- **Location:** Yauco, Puerto Rico (geographic landmark "Sector Primitivo Irizarry" exists in Yauco)
- **Confidence:** CONFIRMED as enslaver; family connection to Keith's ancestry = CONFIRMED via Dolores

---

## CONFIRMED RECORDS — EXTENDED NETWORK (not direct line)

### Miguel Mestres — Belén Connection ⚠️ ACTIVE LEAD
- **Record:** 1940 US Census, Cataño, Puerto Rico
- **Father:** Tomás Mestres (~1910); **Mother:** Belén (~1912)
- **Significance:** A woman named/surnamed Belén married into the Mestres family ~1929–1930. Could be related to Silvia Belén's father.
- **URL:** ancestry.com/1940-census/usa/Puerto-Rico/Miguel-Mestres_5mp41f

### Gregorio Echevarría (~1770–1820) — Early Echevarría in Yauco Region
- **Born:** ~1770, Peñuelas, PR  |  **Died:** December 4, 1820, Peñuelas
- **Mother:** Gregoria Echevarría Y Troche  |  **Spouse:** Dorotea Ortiz
- **Significance:** Establishes Echevarría surname in Yauco region going back to ~1770

### Benigna Echevarría — Active in Guánica ~1919 ✅ (same person as confirmed above)
- Confirmed as mother of Pedro Juan López Echevarria (Oct 22, 1919, Guánica)
- Same Benigna Echevarría who married Eustaquio López in 1907

---

## TIMELINE — KEY CONFIRMED EVENTS

| Year | Event | Source |
|------|-------|--------|
| ~1818 | María Almodovar Echevarría born, Guánica | Death cert (age 110) |
| ~1820 | Felipe (enslaved, pardo) born, Puerto Rico | 1872 Slave Registry |
| ~1864 | Dolores Echevarría born, Guánica | Death cert |
| 1872 | Slave Registry: Felipe (52) under Juan Irizarry, Yauco District 5 | FamilySearch #177782 |
| 1873 | Puerto Rico abolition — enslaved persons adopt surnames | Historical record |
| ~1885 | Eustaquio López y Ortiz born, Yauco | 1907 marriage record |
| 13 Mar 1888 | Benigna Echevarría born | Death cert |
| 1889 | Pedro Mestre Vázquez born | FamilySearch L812-RM7 |
| 16 Jun 1907 | Benigna Echevarría + Eustaquio López married, Yauco | Marriage record |
| 28 Apr 1912 | María Inés López Echevarría born, Guánica | ACTA DE NACIMIENTO |
| 22 Oct 1919 | Pedro Juan López Echevarria born, Guánica | Ancestry record |
| 17 Jan 1928 | María Almodovar Echevarría dies, age 110, Guánica | Death cert No. 409 |
| 10 Dec 1950 | Dolores Echevarría dies, age 86, Barrio Carenero, Guánica | Death cert No. 143 |
| 1962 | Pedro Mestre Vázquez dies | FamilySearch L812-RM7 |
| 19 Jul 1981 | Benigna Echevarría dies, age 93, Ponce | Death cert No. 152 |
| 2013 | María Inés López Echevarría dies, age 101 | Oral history |

---

## COLLECTION ACCESS GUIDE — Exact Search Paths
## Updated: April 17, 2026 (v2 — direct ARK links added from live web research)

### Civil Records (1885–present)
- **FamilySearch Collection 1682798** — familysearch.org/en/search/collection/1682798
  - Pre-1914 Guánica: browse under **Yauco**
  - Post-1914 Guánica: browse under **Guánica**
- **Ancestry collection 9100** — parallel index, cross-reference

### Catholic Church Records — ALL PUERTO RICO ⭐ NEW COLLECTION DISCOVERED
- **FamilySearch Collection 1807092** — familysearch.org/en/search/collection/1807092
- **Date range:** 1645–2021 (covers EVERYTHING — pre-civil-registration back to colonial era)
- **Record types:** Baptisms, confirmations, marriages, burials
- **Access:** Browse by Municipality → Parish, OR use searchable index
- **CRITICAL:** This is the primary source for pre-1885 records (María Almodovar ~1818, Felipe ~1820, etc.)
- Search Yauco → Santísimo Rosario for all pre-1914 Guánica family records

### Church Records — Yauco (Santísimo Rosario)
- **FamilySearch Catalog #277991** — 1751–1962
- **Third-party index:** hijosdecoamopr.com/indexes-for-church-records-for-puerto-rico/yauco-digitized-church-records-and-its-indexes/

### Church Records — Guánica (San Antonio Abad) — EXACT ARK LINKS ✅
Parish started 1888, BEFORE the 1914 municipal separation. Family in Barrio Carenero after 1888 may appear here, not Yauco's records.

**Baptisms:**
- 1888–1898: familysearch.org/ark:/61903/3:1:3Q9M-CSK9-YTZ7
- 1908–1909: familysearch.org/ark:/61903/3:1:3Q9M-CSK9-YT7J
- 1910–1917: familysearch.org/ark:/61903/3:1:3Q9M-CSK9-YPPP
- 1917–1924: familysearch.org/ark:/61903/3:1:3Q9M-CSK9-YPBQ
- 1924–1929: familysearch.org/ark:/61903/3:1:3Q9M-CSK7-YSRN-F
- 1929–1933: familysearch.org/ark:/61903/3:1:3Q9M-CSK7-YSPB-T

**Marriages:**
- 1885 only: familysearch.org/ark:/61903/3:1:3Q9M-CSK9-YYBC
- 1888–1933: familysearch.org/ark:/61903/3:1:3Q9M-CSK7-YSPC-F
- 1909–1933: familysearch.org/ark:/61903/3:1:3Q9M-CSK9-YR94

**Burials:**
- 1885–1899: familysearch.org/ark:/61903/3:1:3Q9M-CSK9-YYNQ

**Confirmations:**
- 1914–1941: familysearch.org/ark:/61903/3:1:3Q9M-CSK7-YSPT-S

### Slavery Records — EXACT LINKS ✅
- **Yauco 1872 Slave Registry (District 5) DIRECT LINK:**
  familysearch.org/ark:/61903/3:1:3QS7-898C-9VHD?i=376&cat=177782
  — District 5 includes: Peñuelas, Adjuntas, Guayanilla, Coamo, **Yauco**
  — Records contain: name, physical description, age, children, owner's name
  — Must browse manually (no keyword search by enslaver name)
- **FamilySearch Catalog #177782** — full Registro Central de Esclavos, 1872
- **Ancestry collection 2774** — parallel index
- **Fold3** — NARA Microfilm T1121, 8 rolls
- **FamilySearch collection 3755445** — Puerto Rico, Slave Registers, 1859–1880

### US Census (1910–1940)
- All four years fully searchable on FamilySearch and Ancestry
- **1910 microfilm:** Reel 1782 (EDs 541-549) and Reel 1783 (EDs 550-572)
- **1920 microfilm:** T625, Roll 60
- In 1910, Guánica was still part of Yauco — look under Yauco for Carenero residents

---

## PRIORITY RESEARCH TASKS

### CRITICAL — Do These First

1. **Resolve María Echevarría vs. María Almodovar Echevarría** — are they the same person?
   - Determines whether to add an extra generation to the tree

2. **Pull Pedro Mestre Vázquez full FamilySearch profile (L812-RM7)**
   - Get birth location, death location, parents' names (especially Vázquez mother)
   - Investigate whether Pedro Vázquez + José Vázquez from Sabana Grande (María Almodovar death witnesses) connect here

3. **Search 1920 and 1930 Census for Pedro Mestre Vázquez household**
   - Find Keith's grandfather as a child — get his full name and birth year

4. **Search Guánica civil records for Keith's grandfather's birth**
   - Son of Pedro Mestre Vázquez, born est. 1915–1945

5. **Find Silvia Belén's marriage record**
   - Will give her father's first name (surname = Belén) and her maternal surname

### OPEN QUESTIONS TO RESOLVE

| Question | Notes |
|---|---|
| Is María Echevarría = María Almodovar Echevarría? | Determines generations in the tree |
| Who married Silvia Belén — and what is her father's first name? | Marriage record in Guánica/Yauco civil records |
| What is Keith's grandfather's full name and birth year? | Find in census under Pedro Mestre Vázquez household |
| What are Pedro Mestre Vázquez's parents' names? | His mother was Vázquez — pull FamilySearch profile |
| Who are Pedro Villa's parents? | Extends the line above Benigna's paternal side |
| Who are Elías López's parents? | He was from Peñuelas |
| Is Ventura Echevarría a sibling of Dolores Echevarría, or a generation above? | Depends on María Echevarría disambiguation |
| Who are Felipe's parents? | Deep ancestry, pre-1820 Puerto Rico |
| What was the Echevarría enslaver's connection to Irizarry? | Both surnames appear — one may be the 1873 adoption surname |
